// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: pkg/api/aegis.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AegisService_GetStatus_FullMethodName       = "/aegis.api.v1.AegisService/GetStatus"
	AegisService_RunScan_FullMethodName         = "/aegis.api.v1.AegisService/RunScan"
	AegisService_TriggerResponse_FullMethodName = "/aegis.api.v1.AegisService/TriggerResponse"
	AegisService_GetTimeline_FullMethodName     = "/aegis.api.v1.AegisService/GetTimeline"
)

// AegisServiceClient is the client API for AegisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AegisServiceClient interface {
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	RunScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResult], error)
	TriggerResponse(ctx context.Context, in *ResponseRequest, opts ...grpc.CallOption) (*ResponseResponse, error)
	GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TimelineEvent], error)
}

type aegisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAegisServiceClient(cc grpc.ClientConnInterface) AegisServiceClient {
	return &aegisServiceClient{cc}
}

func (c *aegisServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AegisService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisServiceClient) RunScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AegisService_ServiceDesc.Streams[0], AegisService_RunScan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisService_RunScanClient = grpc.ServerStreamingClient[ScanResult]

func (c *aegisServiceClient) TriggerResponse(ctx context.Context, in *ResponseRequest, opts ...grpc.CallOption) (*ResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseResponse)
	err := c.cc.Invoke(ctx, AegisService_TriggerResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisServiceClient) GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TimelineEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AegisService_ServiceDesc.Streams[1], AegisService_GetTimeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TimelineRequest, TimelineEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisService_GetTimelineClient = grpc.ServerStreamingClient[TimelineEvent]

// AegisServiceServer is the server API for AegisService service.
// All implementations must embed UnimplementedAegisServiceServer
// for forward compatibility.
type AegisServiceServer interface {
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	RunScan(*ScanRequest, grpc.ServerStreamingServer[ScanResult]) error
	TriggerResponse(context.Context, *ResponseRequest) (*ResponseResponse, error)
	GetTimeline(*TimelineRequest, grpc.ServerStreamingServer[TimelineEvent]) error
	mustEmbedUnimplementedAegisServiceServer()
}

// UnimplementedAegisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAegisServiceServer struct{}

func (UnimplementedAegisServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAegisServiceServer) RunScan(*ScanRequest, grpc.ServerStreamingServer[ScanResult]) error {
	return status.Error(codes.Unimplemented, "method RunScan not implemented")
}
func (UnimplementedAegisServiceServer) TriggerResponse(context.Context, *ResponseRequest) (*ResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerResponse not implemented")
}
func (UnimplementedAegisServiceServer) GetTimeline(*TimelineRequest, grpc.ServerStreamingServer[TimelineEvent]) error {
	return status.Error(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedAegisServiceServer) mustEmbedUnimplementedAegisServiceServer() {}
func (UnimplementedAegisServiceServer) testEmbeddedByValue()                      {}

// UnsafeAegisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AegisServiceServer will
// result in compilation errors.
type UnsafeAegisServiceServer interface {
	mustEmbedUnimplementedAegisServiceServer()
}

func RegisterAegisServiceServer(s grpc.ServiceRegistrar, srv AegisServiceServer) {
	// If the following call panics, it indicates UnimplementedAegisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AegisService_ServiceDesc, srv)
}

func _AegisService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisService_RunScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AegisServiceServer).RunScan(m, &grpc.GenericServerStream[ScanRequest, ScanResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisService_RunScanServer = grpc.ServerStreamingServer[ScanResult]

func _AegisService_TriggerResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisServiceServer).TriggerResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisService_TriggerResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisServiceServer).TriggerResponse(ctx, req.(*ResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisService_GetTimeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TimelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AegisServiceServer).GetTimeline(m, &grpc.GenericServerStream[TimelineRequest, TimelineEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisService_GetTimelineServer = grpc.ServerStreamingServer[TimelineEvent]

// AegisService_ServiceDesc is the grpc.ServiceDesc for AegisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AegisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.api.v1.AegisService",
	HandlerType: (*AegisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _AegisService_GetStatus_Handler,
		},
		{
			MethodName: "TriggerResponse",
			Handler:    _AegisService_TriggerResponse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunScan",
			Handler:       _AegisService_RunScan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTimeline",
			Handler:       _AegisService_GetTimeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/api/aegis.proto",
}
