// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/api/aegis.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_api_aegis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CpuUsage         float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage         float64                `protobuf:"fixed64,4,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	YaraRulesLoaded  int32                  `protobuf:"varint,5,opt,name=yara_rules_loaded,json=yaraRulesLoaded,proto3" json:"yara_rules_loaded,omitempty"`
	SigmaRulesLoaded int32                  `protobuf:"varint,6,opt,name=sigma_rules_loaded,json=sigmaRulesLoaded,proto3" json:"sigma_rules_loaded,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_api_aegis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *StatusResponse) GetRamUsage() float64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *StatusResponse) GetYaraRulesLoaded() int32 {
	if x != nil {
		return x.YaraRulesLoaded
	}
	return 0
}

func (x *StatusResponse) GetSigmaRulesLoaded() int32 {
	if x != nil {
		return x.SigmaRulesLoaded
	}
	return 0
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_pkg_api_aegis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{2}
}

func (x *ScanRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ScanRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Matched       bool                   `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	MatchRule     string                 `protobuf:"bytes,3,opt,name=match_rule,json=matchRule,proto3" json:"match_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_pkg_api_aegis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ScanResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *ScanResult) GetMatchRule() string {
	if x != nil {
		return x.MatchRule
	}
	return ""
}

type ResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	TargetPid     int32                  `protobuf:"varint,2,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	TargetFile    string                 `protobuf:"bytes,3,opt,name=target_file,json=targetFile,proto3" json:"target_file,omitempty"`
	SecurityToken string                 `protobuf:"bytes,4,opt,name=security_token,json=securityToken,proto3" json:"security_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRequest) Reset() {
	*x = ResponseRequest{}
	mi := &file_pkg_api_aegis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRequest) ProtoMessage() {}

func (x *ResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRequest.ProtoReflect.Descriptor instead.
func (*ResponseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ResponseRequest) GetTargetPid() int32 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

func (x *ResponseRequest) GetTargetFile() string {
	if x != nil {
		return x.TargetFile
	}
	return ""
}

func (x *ResponseRequest) GetSecurityToken() string {
	if x != nil {
		return x.SecurityToken
	}
	return ""
}

type ResponseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ActionExecuted string                 `protobuf:"bytes,3,opt,name=action_executed,json=actionExecuted,proto3" json:"action_executed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseResponse) Reset() {
	*x = ResponseResponse{}
	mi := &file_pkg_api_aegis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseResponse) ProtoMessage() {}

func (x *ResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseResponse.ProtoReflect.Descriptor instead.
func (*ResponseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseResponse) GetActionExecuted() string {
	if x != nil {
		return x.ActionExecuted
	}
	return ""
}

type TimelineRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartTimeEpoch int64                  `protobuf:"varint,1,opt,name=start_time_epoch,json=startTimeEpoch,proto3" json:"start_time_epoch,omitempty"`
	EndTimeEpoch   int64                  `protobuf:"varint,2,opt,name=end_time_epoch,json=endTimeEpoch,proto3" json:"end_time_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimelineRequest) Reset() {
	*x = TimelineRequest{}
	mi := &file_pkg_api_aegis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineRequest) ProtoMessage() {}

func (x *TimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineRequest.ProtoReflect.Descriptor instead.
func (*TimelineRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{6}
}

func (x *TimelineRequest) GetStartTimeEpoch() int64 {
	if x != nil {
		return x.StartTimeEpoch
	}
	return 0
}

func (x *TimelineRequest) GetEndTimeEpoch() int64 {
	if x != nil {
		return x.EndTimeEpoch
	}
	return 0
}

type TimelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEvent) Reset() {
	*x = TimelineEvent{}
	mi := &file_pkg_api_aegis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEvent) ProtoMessage() {}

func (x *TimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aegis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEvent.ProtoReflect.Descriptor instead.
func (*TimelineEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_aegis_proto_rawDescGZIP(), []int{7}
}

func (x *TimelineEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TimelineEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TimelineEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TimelineEvent) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

var File_pkg_api_aegis_proto protoreflect.FileDescriptor

const file_pkg_api_aegis_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/api/aegis.proto\x12\faegis.api.v1\"\x0f\n" +
	"\rStatusRequest\"\xd6\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x04 \x01(\x01R\bramUsage\x12*\n" +
	"\x11yara_rules_loaded\x18\x05 \x01(\x05R\x0fyaraRulesLoaded\x12,\n" +
	"\x12sigma_rules_loaded\x18\x06 \x01(\x05R\x10sigmaRulesLoaded\"?\n" +
	"\vScanRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"b\n" +
	"\n" +
	"ScanResult\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x12\x1d\n" +
	"\n" +
	"match_rule\x18\x03 \x01(\tR\tmatchRule\"\x90\x01\n" +
	"\x0fResponseRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x02 \x01(\x05R\ttargetPid\x12\x1f\n" +
	"\vtarget_file\x18\x03 \x01(\tR\n" +
	"targetFile\x12%\n" +
	"\x0esecurity_token\x18\x04 \x01(\tR\rsecurityToken\"o\n" +
	"\x10ResponseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0faction_executed\x18\x03 \x01(\tR\x0eactionExecuted\"a\n" +
	"\x0fTimelineRequest\x12(\n" +
	"\x10start_time_epoch\x18\x01 \x01(\x03R\x0estartTimeEpoch\x12$\n" +
	"\x0eend_time_epoch\x18\x02 \x01(\x03R\fendTimeEpoch\"\x8a\x01\n" +
	"\rTimelineEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x01R\triskScore2\xb7\x02\n" +
	"\fAegisService\x12F\n" +
	"\tGetStatus\x12\x1b.aegis.api.v1.StatusRequest\x1a\x1c.aegis.api.v1.StatusResponse\x12@\n" +
	"\aRunScan\x12\x19.aegis.api.v1.ScanRequest\x1a\x18.aegis.api.v1.ScanResult0\x01\x12P\n" +
	"\x0fTriggerResponse\x12\x1d.aegis.api.v1.ResponseRequest\x1a\x1e.aegis.api.v1.ResponseResponse\x12K\n" +
	"\vGetTimeline\x12\x1d.aegis.api.v1.TimelineRequest\x1a\x1b.aegis.api.v1.TimelineEvent0\x01B\x17Z\x15aegis-edr/pkg/api;apib\x06proto3"

var (
	file_pkg_api_aegis_proto_rawDescOnce sync.Once
	file_pkg_api_aegis_proto_rawDescData []byte
)

func file_pkg_api_aegis_proto_rawDescGZIP() []byte {
	file_pkg_api_aegis_proto_rawDescOnce.Do(func() {
		file_pkg_api_aegis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_aegis_proto_rawDesc), len(file_pkg_api_aegis_proto_rawDesc)))
	})
	return file_pkg_api_aegis_proto_rawDescData
}

var file_pkg_api_aegis_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_api_aegis_proto_goTypes = []any{
	(*StatusRequest)(nil),    // 0: aegis.api.v1.StatusRequest
	(*StatusResponse)(nil),   // 1: aegis.api.v1.StatusResponse
	(*ScanRequest)(nil),      // 2: aegis.api.v1.ScanRequest
	(*ScanResult)(nil),       // 3: aegis.api.v1.ScanResult
	(*ResponseRequest)(nil),  // 4: aegis.api.v1.ResponseRequest
	(*ResponseResponse)(nil), // 5: aegis.api.v1.ResponseResponse
	(*TimelineRequest)(nil),  // 6: aegis.api.v1.TimelineRequest
	(*TimelineEvent)(nil),    // 7: aegis.api.v1.TimelineEvent
}
var file_pkg_api_aegis_proto_depIdxs = []int32{
	0, // 0: aegis.api.v1.AegisService.GetStatus:input_type -> aegis.api.v1.StatusRequest
	2, // 1: aegis.api.v1.AegisService.RunScan:input_type -> aegis.api.v1.ScanRequest
	4, // 2: aegis.api.v1.AegisService.TriggerResponse:input_type -> aegis.api.v1.ResponseRequest
	6, // 3: aegis.api.v1.AegisService.GetTimeline:input_type -> aegis.api.v1.TimelineRequest
	1, // 4: aegis.api.v1.AegisService.GetStatus:output_type -> aegis.api.v1.StatusResponse
	3, // 5: aegis.api.v1.AegisService.RunScan:output_type -> aegis.api.v1.ScanResult
	5, // 6: aegis.api.v1.AegisService.TriggerResponse:output_type -> aegis.api.v1.ResponseResponse
	7, // 7: aegis.api.v1.AegisService.GetTimeline:output_type -> aegis.api.v1.TimelineEvent
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_aegis_proto_init() }
func file_pkg_api_aegis_proto_init() {
	if File_pkg_api_aegis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_aegis_proto_rawDesc), len(file_pkg_api_aegis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_aegis_proto_goTypes,
		DependencyIndexes: file_pkg_api_aegis_proto_depIdxs,
		MessageInfos:      file_pkg_api_aegis_proto_msgTypes,
	}.Build()
	File_pkg_api_aegis_proto = out.File
	file_pkg_api_aegis_proto_goTypes = nil
	file_pkg_api_aegis_proto_depIdxs = nil
}
